FROM java:7-jdk-alpine
# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD tmp /app/android-keystore-password-recover
COPY launch_jar.sh /app/launch_jar.sh
RUN chmod +x /app/launch_jar.sh

WORKDIR /app/android-keystore-password-recover
RUN /app/android-keystore-password-recover/build.sh